### PR TITLE
Fix star chart not showing up.

### PR DESCRIPTION
**Pull request by EchoQuill**
seems like you forgot to update username for the Starchart after changing your Github username.
This pull request fixes that.

### CODE REVIEW

**Comment by iamz4ri** [comment]
appreciate it, but it isnt necessary.. no1 cares about the readme

**Comment by EchoQuill** [comment]
> appreciate it, but it isnt necessary.. no1 cares about the readme

hm alright!, do I close this PR?

**Comment by iamz4ri** [comment]
> > appreciate it, but it isnt necessary.. no1 cares about the readme
> 
> hm alright!, should I close this PR?

i would edit it later, so whatever

**Comment by EchoQuill** [comment]
> > > appreciate it, but it isnt necessary.. no1 cares about the readme
> > 
> > 
> > hm alright!, should I close this PR?
> 
> i would edit it later, so whatever

alright, I appreciate your time :>

**Pull request closed without merging**
